baseURL = 'https://kaorz.com/blog/'
languageCode = 'zh-CN'
title = '阿伟的部落格'
theme = 'blowfish'
defaultContentLanguage = 'zh-cn'
enableRobotsTXT = true

[languages]
  [languages.zh-cn]
    languageCode = 'zh-CN'
    contentDir = 'content'
    weight = 1
    title = '阿伟的部落格'
    locale = 'zh-CN'

[pagination]
  pagerSize = 20

[params]
  colorScheme = 'slate'
  defaultAppearance = 'light'
  autoSwitchAppearance = true
  enableSearch = true
  enableCodeCopy = true
  mainSections = ['posts', 'archives']

  [params.header]
    layout = 'basic'

  [params.footer]
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

  [params.homepage]
    layout = 'hero'
    homepageImage = 'img/hero.jpg'
    showRecent = true
    showRecentItems = 3
    showMoreLink = true
    showMoreLinkDest = 'posts'
    cardView = false
    disableHeroImageFilter = false

  [params.article]
    showDate = true
    showAuthor = true
    showReadingTime = true
    showWordCount = true
    showPagination = true
    showBreadcrumbs = true
    showTableOfContents = true   # 显示目录
    showTaxonomies = true        # 显示标签/分类
    showAuthorsBadges = true     # 显示作者徽章
    heroStyle = "thumbAndBackground"          # big, basic, background, thumbAndBackground

  [params.list]
    showSummary = true
    showHero = true          # 列表页不需要大图
    groupByYear = true
    showBreadcrumbs = true
    orderByWeight = true     # 按日期排序

[[menu.main]]
  name = '文章'
  pageRef = 'posts'
  weight = 1

[[menu.main]]
  name = '标签'
  pageRef = 'tags'
  weight = 2

[markup]
  [markup.highlight]
    noClasses = false

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[params.authors]
  [params.authors.wynne]
    name = "wynne"
    image = "img/avatar.jpg"
    bio = "Hi, there~"
    links = [
      ["github", "https://github.com/wynn719"],
    ]
